using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Xml.Linq;
using JumpKing.Mods;
using JumpKing.PauseMenu;
using JKRuntime.Modules;

namespace JKRuntime
{
    // The only reflection rendezvous, generated by the SDK. Game discovery
    // completes before this executes. Embedded assemblies are never native mods.
    public static class PackageHost
    {
        private sealed class Package
        {
            internal string Id, Directory, Error;
            internal Assembly Shell, Implementation;
            internal Type Entry;
            internal Action Before, End;
            internal PreparationLifetime Preparation;
            internal bool Active;
            internal bool MapOwned;
            internal IDisposable Registration;
        }
        private sealed class PackageDependency
        {
            internal string FullName, File, Sha256;
        }
        private static readonly Dictionary<string, Package> packages = new Dictionary<string, Package>(StringComparer.Ordinal);
        private static readonly HashSet<Assembly> seen = new HashSet<Assembly>();
        private static readonly Dictionary<Assembly, Assembly> implementations = new Dictionary<Assembly, Assembly>();
        private static readonly ConcurrentDictionary<Assembly, string> implementationDirectories = new ConcurrentDictionary<Assembly, string>();
        private static readonly ConcurrentDictionary<Assembly, Dictionary<string, PackageDependency>> implementationDependencies = new ConcurrentDictionary<Assembly, Dictionary<string, PackageDependency>>();
        private static readonly List<string> errors = new List<string>();
        private static string[] preparationOrder = new string[0];
        static PackageHost()
        {
            // Assembly.Load(byte[]) has no load-from context. Resolve only our
            // SDK contract for implementations we actually own, not other mods.
            AppDomain.CurrentDomain.AssemblyResolve += delegate(object sender, ResolveEventArgs args) {
                if (args.RequestingAssembly == null || !implementationDirectories.ContainsKey(args.RequestingAssembly)) return null;
                if (args.Name == typeof(RuntimeApi).Assembly.FullName) return typeof(RuntimeApi).Assembly;
                Assembly owned = implementationDirectories.Keys.FirstOrDefault(a => a.FullName == args.Name);
                if (owned != null) return owned;
                Dictionary<string, PackageDependency> allowed;
                PackageDependency dependency;
                string requestedName = new AssemblyName(args.Name).Name;
                if (!implementationDependencies.TryGetValue(args.RequestingAssembly, out allowed)
                    || !allowed.TryGetValue(requestedName, out dependency)
                    || !string.Equals(args.Name, dependency.FullName, StringComparison.Ordinal)) return null;
                Assembly loaded = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.FullName == dependency.FullName);
                if (loaded != null) return loaded;
                string directory = implementationDirectories[args.RequestingAssembly];
                string path = Path.GetFullPath(Path.Combine(directory, dependency.File));
                string prefix = Path.GetFullPath(directory).TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;
                if (!path.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) || !File.Exists(path)) return null;
                using (var stream = File.OpenRead(path))
                using (var sha = SHA256.Create())
                    if (BitConverter.ToString(sha.ComputeHash(stream)).Replace("-", "") != dependency.Sha256)
                        throw new InvalidDataException("Package dependency checksum mismatch: " + dependency.File);
                if (AssemblyName.GetAssemblyName(path).FullName != dependency.FullName)
                    throw new InvalidDataException("Package dependency identity mismatch: " + dependency.File);
                return Assembly.LoadFrom(path);
            };
        }
        public static string[] Errors { get { return errors.Concat(packages.Values.Where(p => p.Preparation.Error != null)
            .Select(p => p.Id + " preparation: " + p.Preparation.Error)).ToArray(); } }
        internal static object[] InspectPreparation()
        { return packages.Values.OrderBy(p => p.Id).Select(p => p.Preparation.Inspect()).ToArray(); }
        // Keep the shell's public binding identity while reading live settings
        // from its implementation. Foreign mods retain their native assembly.
        internal static Assembly BindingAssembly(Assembly shell)
        {
            Assembly implementation;
            return implementations.TryGetValue(shell, out implementation) ? implementation : shell;
        }
        public static void Discover()
        { DiscoverAssemblies(ModLoader.Instance.LoadedMods.ToArray().Select(mod => mod.Assembly), false); }
        // Map packages use a non-DLL shell suffix: Worldsmith treats any root
        // DLL as a mod, while the native local loader recursively scans DLLs.
        internal static void DiscoverMap(string root)
        {
            Discover();
            string directory = Path.Combine(Path.GetFullPath(root), "jk-runtime", "modules");
            if (!Directory.Exists(directory)) return;
            var shells = new List<Assembly>();
            foreach (string folder in Directory.GetDirectories(directory).OrderBy(p => p, StringComparer.Ordinal))
                foreach (string path in Directory.GetFiles(folder, "*.jkmod").OrderBy(p => p, StringComparer.Ordinal))
                {
                    Assembly shell = Assembly.LoadFrom(path);
                    using (var manifest = shell.GetManifestResourceStream("JKRuntime.Manifest"))
                        if (manifest == null) throw new InvalidDataException("Map package has no Runtime manifest: " + path);
                    shells.Add(shell);
                }
            DiscoverAssemblies(shells, true);
        }
        internal static void ReleaseMapPackages()
        {
            foreach (var package in packages.Values.Where(p => p.MapOwned).ToArray())
            {
                package.Registration.Dispose();
                packages.Remove(package.Id);
                seen.Remove(package.Shell);
            }
        }
        private static void DiscoverAssemblies(IEnumerable<Assembly> shells, bool mapOwned)
        {
            RuntimeHost.Initialize();
            var pending = new List<KeyValuePair<Assembly, XElement>>();
            foreach (var shell in shells)
            {
                if (seen.Contains(shell)) continue;
                using (Stream stream = shell.GetManifestResourceStream("JKRuntime.Manifest"))
                {
                    if (stream == null)
                    {
                        // Resources of a loaded file assembly are immutable.
                        // Foreign mods have no SDK manifest; remember that too.
                        if (!shell.IsDynamic) seen.Add(shell);
                        continue;
                    }
                    seen.Add(shell);
                    try
                    {
                        var manifest = XElement.Load(stream);
                        if (!implementations.ContainsKey(shell)) LoadImplementation(shell, manifest);
                        pending.Add(new KeyValuePair<Assembly, XElement>(shell, manifest));
                    }
                    catch (Exception error) { errors.Add(shell.GetName().Name + ": " + error); Console.WriteLine("[JK Runtime] " + errors.Last()); }
                }
            }
            // Load every owned implementation before resolving entry/method
            // types: an SDK client may expose types from another module.
            foreach (var item in pending)
                try { Load(item.Key, item.Value, mapOwned); }
                catch (Exception error) { errors.Add(item.Key.GetName().Name + ": " + error); Console.WriteLine("[JK Runtime] " + errors.Last()); }
        }
        private static void LoadImplementation(Assembly shell, XElement manifest)
        {
            if ((int)manifest.Attribute("schema") != 1 || (int)manifest.Attribute("apiMajor") != RuntimeApi.ApiMajor
                || (int)manifest.Attribute("apiMinor") > RuntimeApi.ApiMinor)
                throw new InvalidOperationException("Incompatible package schema/API; update the runtime and dependent mods together.");
            byte[] bytes;
            using (var stream = shell.GetManifestResourceStream("JKRuntime.Module"))
            using (var buffer = new MemoryStream())
            { if (stream == null) throw new InvalidDataException("Missing implementation"); stream.CopyTo(buffer); bytes = buffer.ToArray(); }
            using (var sha = SHA256.Create())
                if (BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-", "") != (string)manifest.Attribute("sha256"))
                    throw new InvalidDataException("Package implementation checksum mismatch");
            var implementation = Assembly.Load(bytes);
            string directory = Path.GetDirectoryName(shell.Location);
            implementationDirectories[implementation] = directory;
            var dependencies = new Dictionary<string, PackageDependency>(StringComparer.Ordinal);
            foreach (XElement node in manifest.Elements("assemblyReference"))
            {
                string name = (string)node.Attribute("name");
                string fullName = (string)node.Attribute("fullName");
                string file = (string)node.Attribute("file");
                string expectedHash = (string)node.Attribute("sha256");
                if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(fullName)
                    || string.IsNullOrWhiteSpace(file) || Path.GetFileName(file) != file
                    || !string.Equals(Path.GetExtension(file), ".dll", StringComparison.OrdinalIgnoreCase)
                    || string.IsNullOrWhiteSpace(expectedHash) || expectedHash.Length != 64
                    || new AssemblyName(fullName).Name != name || dependencies.ContainsKey(name))
                    throw new InvalidDataException("Invalid package assemblyReference");
                dependencies.Add(name, new PackageDependency { FullName = fullName, File = file, Sha256 = expectedHash });
            }
            implementationDependencies[implementation] = dependencies;
            if (implementation.GetName().Name != (string)manifest.Attribute("assembly")) throw new InvalidDataException("Wrong implementation identity");
            implementations.Add(shell, implementation);
        }
        private static void Load(Assembly shell, XElement manifest, bool mapOwned)
        {
            string id = (string)manifest.Attribute("id");
            if (packages.ContainsKey(id)) { packages[id].Error = "Duplicate runtime module: " + id; throw new InvalidOperationException(packages[id].Error); }
            var implementation = implementations[shell];
            var entry = implementation.GetType((string)manifest.Attribute("entry"), true);
            var metadata = (RuntimeModuleAttribute)Attribute.GetCustomAttribute(entry, typeof(RuntimeModuleAttribute));
            if (metadata == null || metadata.Id != id) throw new InvalidDataException("Wrong module identity");
            var package = new Package { Id = id, Shell = shell, Implementation = implementation, Entry = entry, MapOwned = mapOwned,
                Directory = Path.GetDirectoryName(shell.Location), Before = Callback<JKRuntime.Modules.BeforeLevelLoadAttribute>(entry),
                End = Callback<JKRuntime.Modules.OnLevelEndAttribute>(entry),
                Preparation = new PreparationLifetime(id, PreparationCallback<OnWorldReadyAttribute>(entry),
                    PreparationCallback<BeforeAttemptAttribute>(entry)) };
            var start = LevelCallback<JKRuntime.Modules.OnLevelStartAttribute>(entry);
            var stop = Callback<JKRuntime.Modules.OnLevelUnloadAttribute>(entry);
            packages.Add(id, package);
            try
            {
                var required = new List<CapabilityRequirement> { new CapabilityRequirement("jk.ui", 1, 0) };
                foreach (var node in manifest.Elements("requires")) {
                    var parts = node.Value.Split(':');
                    if (parts.Length < 3 || parts.Length > 4 || (parts.Length == 4 && parts[3] != "optional")) throw new InvalidDataException("Invalid capability requirement: " + node.Value);
                    required.Add(new CapabilityRequirement(parts[0], int.Parse(parts[1]), int.Parse(parts[2]), parts.Length == 4 && parts[3] == "optional"));
                }
                var provided = new List<CapabilityDefinition>();
                foreach (var node in manifest.Elements("provides")) {
                    var parts = node.Value.Split(':');
                    if (parts.Length != 3) throw new InvalidDataException("Invalid capability definition: " + node.Value);
                    provided.Add(new CapabilityDefinition(parts[0], int.Parse(parts[1]), int.Parse(parts[2])));
                }
                var definition = new ModuleDefinition(id, implementation.GetName().Version,
                    delegate(ModuleContext context) {
                        if (package.Error != null) throw new InvalidOperationException(package.Error);
                        // Late discovery/custom loaders can miss the native intro.
                        package.Preparation.EnsurePrepared();
                        package.Preparation.ThrowIfFailed();
                        context.Track(new ActionLease(delegate { stop(); package.Active = false; }));
                        start(context); package.Active = true;
                    }, required, provided, manifest.Elements("before").Select(e => e.Value), manifest.Elements("after").Select(e => e.Value));
                definition.Origin = implementation.FullName;
                definition.OptionalOrderingTargets = mapOwned;
                definition.MapSuspendable = metadata.MapSuspendable;
                package.Registration = RuntimeApi.Register(definition);
            }
            catch { packages.Remove(id); throw; }
        }
        private static Action Callback<T>(Type entry) where T : Attribute
        {
            MethodInfo method = entry.GetMethods(BindingFlags.Public | BindingFlags.Static).SingleOrDefault(m => m.IsDefined(typeof(T), false));
            return method == null ? (Action)delegate { } : (Action)Delegate.CreateDelegate(typeof(Action), method);
        }
        private static Action<RuntimeScope> PreparationCallback<T>(Type entry) where T : Attribute
        {
            MethodInfo method = entry.GetMethods(BindingFlags.Public | BindingFlags.Static).SingleOrDefault(m => m.IsDefined(typeof(T), false));
            return method == null ? null : (Action<RuntimeScope>)Delegate.CreateDelegate(typeof(Action<RuntimeScope>), method);
        }
        internal static void PrepareAttempt()
        {
            Discover();
            RuntimeApi.Kernel.Prepare(delegate(string[] order) {
                preparationOrder = order;
                foreach (string id in order)
                {
                    Package package;
                    if (packages.TryGetValue(id, out package) && package.Error == null) package.Preparation.Prepare();
                }
            });
        }
        internal static void ReleasePreparation(bool world)
        {
            var failures = new List<Exception>();
            // Include owners rejected by a later graph resolution or interrupted preparation.
            var order = preparationOrder.Concat(packages.Keys.OrderBy(id => id)).Distinct().ToArray();
            foreach (string id in order.Reverse())
            {
                Package package;
                if (!packages.TryGetValue(id, out package)) continue;
                try { if (world) package.Preparation.ReleaseWorld(); else package.Preparation.ReleaseAttempt(); }
                catch (Exception error) { failures.Add(error); }
            }
            if (failures.Count != 0) throw new AggregateException("Module preparation cleanup failed", failures);
        }
        private static Action<ModuleContext> LevelCallback<T>(Type entry) where T : Attribute
        {
            MethodInfo method = entry.GetMethods(BindingFlags.Public | BindingFlags.Static).SingleOrDefault(m => m.IsDefined(typeof(T), false));
            if (method == null) return delegate { };
            if (method.GetParameters().Length == 0) {
                var callback = (Action)Delegate.CreateDelegate(typeof(Action), method);
                return delegate { callback(); };
            }
            return (Action<ModuleContext>)Delegate.CreateDelegate(typeof(Action<ModuleContext>), method);
        }
        internal static void BeforeLevel()
        {
            Discover();
            RuntimeApi.Kernel.ValidateMapPolicy();
            foreach (var package in packages.Values.OrderBy(p => p.Id))
            {
                if (package.Error != null || MapPolicy.Suspends(package.Id)) continue;
                try { package.Before(); }
                catch (Exception error) { package.Error = "BeforeLevelLoad failed: " + error; errors.Add(package.Id + ": " + package.Error); }
            }
        }
        internal static void EndLevel()
        {
            var failures = new List<Exception>();
            foreach (var id in RuntimeApi.GetOrder().Reverse()) {
                Package package;
                if (!packages.TryGetValue(id, out package) || !package.Active) continue;
                try { package.End(); } catch (Exception error) { failures.Add(error); errors.Add(id + " end: " + error); }
            }
            if (failures.Count != 0) throw new AggregateException("Module completion callbacks failed", failures);
        }
        public static object Menu(string id, string method, object factory, GuiFormat format)
        {
            Discover();
            Package package;
            if (!packages.TryGetValue(id, out package)) throw new InvalidOperationException("Module unavailable: " + id + ". See JKRuntime diagnostics.");
            MethodInfo info = package.Entry.GetMethod(method, BindingFlags.Public | BindingFlags.Static);
            if (info == null || (!info.IsDefined(typeof(JKRuntime.Modules.MainMenuItemSettingAttribute), false)
                && !info.IsDefined(typeof(JKRuntime.Modules.PauseMenuItemSettingAttribute), false)))
                throw new InvalidOperationException("Unknown module menu: " + id + "/" + method);
            return info.Invoke(null, new object[] { factory, format });
        }
        internal static MethodInfo MenuImplementation(Assembly shell, MethodInfo menu)
        {
            Discover();
            var package = packages.Values.FirstOrDefault(p => p.Shell == shell);
            return package == null ? menu : package.Entry.GetMethod(menu.Name);
        }
        public static string GetDataDirectory(Assembly implementation)
        {
            string directory;
            if (implementationDirectories.TryGetValue(implementation, out directory)) return directory;
            // Standalone test hosts use a real assembly path, not a second runtime mode.
            if (!string.IsNullOrEmpty(implementation.Location)) return Path.GetDirectoryName(implementation.Location);
            throw new InvalidOperationException("Assembly is not owned by a loaded runtime package");
        }
    }
}
