using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Xml;
using System.Xml.Serialization;

namespace MegaMappingExpansion
{
    // XML names/defaults and live-edit bounds come from the same types used by the loader.
    internal static class SceneContract
    {
        internal static void Write(string directory)
        {
            Directory.CreateDirectory(directory);
            var scene = new SceneFile(); scene.Options.AdvancedLighting = true;
            foreach (PropertyInfo property in typeof(SceneFile).GetProperties())
            {
                if (!property.PropertyType.IsArray) continue;
                Type type = property.PropertyType.GetElementType();
                object item = Activator.CreateInstance(type); PropertyInfo id = type.GetProperty("Id");
                if (id != null) id.SetValue(item, property.Name, null);
                PropertyInfo screen = type.GetProperty("Screen"); if (screen != null) screen.SetValue(item, 1, null);
                var values = Array.CreateInstance(type, 1); values.SetValue(item, 0); property.SetValue(scene, values, null);
            }
            var dynamic = new SceneProperties(scene).Values.Values.GroupBy(p => p.Member.DeclaringType.FullName + "/" + p.Member.Name).ToDictionary(g => g.Key, g => g.First());
            var pending = new Queue<Type>(); pending.Enqueue(typeof(SceneFile)); var visited = new HashSet<Type>();
            var markdown = new StringBuilder("# Generated scene contract\n\nGenerated by `SceneCacheCompiler --reference`. Do not edit. XML names, constructor defaults and effect-editable bounds are read directly from the model and runtime property registry. Structural fields require scene reload. Additional cross-field constraints are documented in the handbook and enforced by the scene validator. `unset` is not a promise that a field is optional.\n\n");
            using (var xml = XmlWriter.Create(Path.Combine(directory, "scene-parameters.xml"), new XmlWriterSettings { Indent = true }))
            {
                xml.WriteStartElement("SceneContract"); xml.WriteAttributeString("version", "1");
                while (pending.Count > 0)
                {
                    Type type = pending.Dequeue(); if (!visited.Add(type)) continue;
                    object baseline = type.IsAbstract ? null : Activator.CreateInstance(type);
                    xml.WriteStartElement("Type"); xml.WriteAttributeString("name", type.Name);
                    markdown.Append("## " + type.Name + "\n\n| XML member | Type | Default | Live effect constraint |\n| --- | --- | --- | --- |\n");
                    foreach (PropertyInfo property in type.GetProperties().OrderBy(p => p.MetadataToken))
                    {
                        if (property.IsDefined(typeof(XmlIgnoreAttribute), true)) continue;
                        var attribute = (XmlAttributeAttribute)Attribute.GetCustomAttribute(property, typeof(XmlAttributeAttribute));
                        var array = (XmlArrayAttribute)Attribute.GetCustomAttribute(property, typeof(XmlArrayAttribute));
                        var elements = property.GetCustomAttributes(typeof(XmlElementAttribute), true).Cast<XmlElementAttribute>().ToArray();
                        var element = elements.FirstOrDefault();
                        if (attribute == null && array == null && element == null) continue;
                        string name = attribute != null ? "@" + attribute.AttributeName : array != null ? array.ElementName : string.Join(" / ", elements.Select(e => e.ElementName));
                        Type valueType = property.PropertyType.IsArray ? property.PropertyType.GetElementType() : property.PropertyType;
                        string kind = property.PropertyType.IsArray ? valueType.Name + "[]" : valueType.Name;
                        string value = property.PropertyType.IsArray ? "empty" : valueType.IsClass && valueType != typeof(string) ? "object" : baseline == null ? "unset" : Format(property.GetValue(baseline, null));
                        SceneProperty live;
                        string edit = "reload";
                        if (dynamic.TryGetValue(type.FullName + "/" + property.Name, out live))
                            edit = live.Color ? "color" : live.Choices != null ? "choice (declared asset IDs or enum)" : property.PropertyType == typeof(bool) ? "boolean" : Format(live.Min) + ".." + Format(live.Max);
                        xml.WriteStartElement("Member"); xml.WriteAttributeString("xml", name); xml.WriteAttributeString("type", kind); xml.WriteAttributeString("default", value); xml.WriteAttributeString("effect", edit);
                        var item = (XmlArrayItemAttribute)Attribute.GetCustomAttribute(property, typeof(XmlArrayItemAttribute));
                        if (item != null) xml.WriteAttributeString("item", item.ElementName);
                        xml.WriteEndElement();
                        markdown.Append("| `" + name + (item == null ? "" : "/" + item.ElementName) + "` | " + kind + " | " + Escape(value) + " | " + Escape(edit) + " |\n");
                        if (valueType.IsClass && valueType != typeof(string)) pending.Enqueue(valueType);
                        foreach (var variant in elements) if (variant.Type != null && variant.Type != typeof(string)) pending.Enqueue(variant.Type);
                    }
                    markdown.Append('\n'); xml.WriteEndElement();
                }
                xml.WriteEndElement();
            }
            File.WriteAllText(Path.Combine(directory, "PARAMETERS_GENERATED.md"), markdown.ToString(), new UTF8Encoding(false));
        }
        private static string Format(object value) { return value == null ? "unset" : value is bool ? ((bool)value ? "true" : "false") : Convert.ToString(value, CultureInfo.InvariantCulture); }
        private static string Escape(string value) { return value.Replace("|", "&#124;").Replace("\r", "").Replace("\n", "<br>"); }
    }
}
